# NixOS kiosk configuration — Yodeck Web Player via Chromium + cage (Wayland)
#
# TWO TARGETS, ONE FILE:
#   1. Testing in a VM on your Apple Silicon Mac (UTM/QEMU, aarch64)
#   2. Real deployment on a Raspberry Pi 4
#
# The differences are isolated in the "VM-ONLY" and "PI-ONLY" blocks below.
# For the VM test, comment out/remove the PI-ONLY block and vice versa.

{ config, pkgs, lib, ... }:

{
  imports = [
    ./hardware-configuration.nix  # generated by `nixos-generate-config` — VM or Pi specific, see notes at bottom
  ];

  # --- Boot ---
  boot.loader.systemd-boot.enable = true;       # VM-ONLY: fine for UEFI VMs
  boot.loader.efi.canTouchEfiVariables = true;  # VM-ONLY
  # PI-ONLY: Pi 4 doesn't use systemd-boot/EFI the same way — see notes at bottom
  # for the nixos-hardware Pi 4 module, which sets up boot correctly instead.

  networking.hostName = "reception-signage";
  networking.networkmanager.enable = true; # simplest way to get wifi/ethernet working; swap for static config if you prefer

  time.timeZone = "Europe/London";

  # --- Auto-login user (kiosk runs as this unprivileged user) ---
  users.users.kiosk = {
    isNormalUser = true;
    description = "Kiosk";
    extraGroups = [ "video" "render" "input" ];
    # no password needed since we're autologging in via getty — set one if you want SSH access
  };

  # --- Autologin on tty1, then start the graphical session ---
  services.getty.autologinUser = "kiosk";

  # --- Wayland kiosk session: cage (minimal single-app compositor) + Chromium ---
  environment.systemPackages = with pkgs; [
    cage
    chromium
  ];

  # Launch cage+Chromium automatically after autologin, on tty1
  programs.bash.loginShellInit = ''
    if [ -z "$DISPLAY" ] && [ "$(tty)" = "/dev/tty1" ]; then
      exec cage -- chromium \
        --ozone-platform=wayland \
        --kiosk \
        --noerrdialogs \
        --disable-infobars \
        --disable-session-crashed-bubble \
        --autoplay-policy=no-user-gesture-required \
        --start-fullscreen \
        "https://player.yodeck.com"
    fi
  '';

  # --- Resilience: if Chromium/cage crashes, the shell exits and getty
  # respawns it automatically since autologin re-triggers loginShellInit.
  # Optional extra safety net via systemd if you want more control/logging
  # instead of the loginShellInit approach above — ask if you'd rather do it
  # as a proper systemd service with Restart=always and journal logging.

  # --- Audio (for the Yodeck PWA install, which enables autoplay with sound) ---
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    pulse.enable = true;
  };

  # --- Networking basics ---
  networking.firewall.enable = true;

  system.stateVersion = "24.11";
}

# ============================================================
# NOTES
# ============================================================
#
# TESTING IN A VM (Apple Silicon Mac via UTM/QEMU):
#   - Download the NixOS aarch64 minimal/graphical ISO.
#   - Create a UTM VM: architecture "Apple Virtualization" or QEMU aarch64,
#     at least 2GB RAM, virtio-gpu display.
#   - Boot ISO, run `nixos-generate-config`, drop this file in as
#     configuration.nix (adjusting hardware-configuration.nix as generated),
#     then `nixos-rebuild switch`.
#   - You'll be able to test: autologin, cage launching, Chromium kiosk mode,
#     registering the Web Player against your Yodeck account, and the PWA
#     install for sound. Genuinely useful signal before touching the Pi.
#   - What you WON'T be testing: Pi-specific GPU/video-decode behavviour
#     (VideoCore driver), since the VM uses virtio-gpu. Video playback
#     smoothness needs verifying on the actual Pi 4.
#
# MOVING TO THE REAL PI 4:
#   - Use the NixOS Raspberry Pi 4 install method (SD card image built via
#     nixos-generate or the community Pi installer) rather than the generic
#     ISO — this gets you the right kernel/firmware.
#   - Pull in `nixos-hardware`'s raspberry-pi-4 module in your imports for
#     correct GPU/firmware/boot handling:
#       inputs.nixos-hardware.url = "github:NixOS/nixos-hardware/master";
#       imports = [ nixos-hardware.nixosModules.raspberry-pi-4 ... ];
#   - Remove the systemd-boot/EFI lines above — the Pi 4 module handles boot.
#   - Everything else (users, autologin, cage, Chromium kiosk line, pipewire)
#     carries over unchanged.
#
# YODECK-SPECIFIC STEPS (do these once Chromium is up and pointed at
# https://player.yodeck.com):
#   1. It'll show a registration code — paste that into your Yodeck portal
#      to link the screen.
#   2. Install it as a PWA (via Chromium's install prompt/menu) to enable
#      autoplay with sound — otherwise videos play muted.
#   3. If you want remote screenshots/previews in the Yodeck dashboard,
#      that needs their Chrome Extension, which is a separate install step
#      and may need `--load-extension` flags or manual install on first run.
